FROM golang:1.25.4-alpine3.22 AS build
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go mod download && go build -o server main.go

FROM alpine:3.22 AS final
WORKDIR /app
COPY --from=build /app/server .

EXPOSE 8080
CMD ["./server"]
